### ISSUE TITLE
Need of opendht ?

### ISSUE THREAD

**Issue by Harold-Glitch** [novemus/plexus#3]
Not really an issue, but for the DHT implementation, is there a way to get libs for OpenDHT because I cannot build it under Windows ?

**Comment by novemus** [comment]
Yes. If you need the static library, you can build it from the code of the original OpenDHT repository. For that you will need to download some dependencies that cmake will require, because the build script doesn't do this. I recommend doing this using vcpkg. Then pass the dependencies to cmake build with PKG_CONFIG_PATH. Unfortunately, the original cmake script doesn't work for the shared build. I suggested [PR](https://github.com/savoirfairelinux/opendht/pull/716) to solve this problem, but for some reason it has not been accepted yet. You can clone my OpenDHT fork, synchronize it with the original repo and build OpenDHT as you want. There is an [instruction](https://github.com/savoirfairelinux/opendht/pull/716#issue-2399219829) in PR how to build OpenDHT under Windows.  By the way, the plexus is linked with the static OpenDHT library.
